services:
    connect:
        restart: unless-stopped
        image: ghcr.io/powerhouse-inc/connect:develop
        environment:
            PORT: 3000
            BASE_PATH: "/"
            PH_CONNECT_ROUTER_BASENAME: "/"
        ports:
            - ${CONNECT_PORT}:3000
