services:
    redis:
        image: redis:6.2-alpine
        restart: always
        ports:
            - "6380:6379"

    database:
        restart: unless-stopped
        image: postgres:15
        ports:
            - 5444:5432
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_PORT: "5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 1s
            timeout: 5s
            retries: 5
