services:
    connect:
        restart: unless-stopped
        image: ghcr.io/powerhouse-inc/connect:develop
        environment:
            PORT: 3000
            BASE_PATH: "/"
            PH_CONNECT_ROUTER_BASENAME: ${PH_CONNECT_ROUTER_BASENAME-/}
            PH_CONNECT_DEFAULT_DRIVES_URL: ${PH_CONNECT_DEFAULT_DRIVES_URL-https://apps.powerhouse.io/develop/powerhouse/switchboard/d/core-dev}
            PH_CONNECT_ENABLED_EDITORS: ${PH_CONNECT_ENABLED_EDITORS-*}
            PH_CONNECT_DISABLE_ADD_PUBLIC_DRIVES: ${PH_CONNECT_DISABLE_ADD_PUBLIC_DRIVES-false}
            PH_CONNECT_SEARCH_BAR_ENABLED: ${PH_CONNECT_SEARCH_BAR_ENABLED-false}
            PH_CONNECT_DISABLE_ADD_CLOUD_DRIVES: ${PH_CONNECT_DISABLE_ADD_CLOUD_DRIVES-false}
            PH_CONNECT_DISABLE_ADD_LOCAL_DRIVES: ${PH_CONNECT_DISABLE_ADD_LOCAL_DRIVES-false}
            PH_CONNECT_DISABLE_DELETE_PUBLIC_DRIVES: ${PH_CONNECT_DISABLE_DELETE_PUBLIC_DRIVES-false}
            PH_CONNECT_DISABLE_DELETE_CLOUD_DRIVES: ${PH_CONNECT_DISABLE_DELETE_CLOUD_DRIVES-false}
            PH_CONNECT_DISABLE_DELETE_LOCAL_DRIVES: ${PH_CONNECT_DISABLE_DELETE_LOCAL_DRIVES-false}
            PH_CONNECT_PUBLIC_DRIVES_ENABLED: ${PH_CONNECT_PUBLIC_DRIVES_ENABLED-true}
            PH_CONNECT_CLOUD_DRIVES_ENABLED: ${PH_CONNECT_CLOUD_DRIVES_ENABLED-true}
            PH_CONNECT_LOCAL_DRIVES_ENABLED: ${PH_CONNECT_LOCAL_DRIVES_ENABLED-true}
            PH_CONNECT_RWA_ALLOW_LIST: ${PH_CONNECT_RWA_ALLOW_LIST-*}
            PH_CONNECT_HIDE_DOCUMENT_MODEL_SELECTION_SETTINGS: ${PH_CONNECT_HIDE_DOCUMENT_MODEL_SELECTION_SETTINGS-true}
            PH_CONNECT_RENOWN_URL: ${PH_CONNECT_RENOWN_URL-https://www.renown.id}
            PH_CONNECT_RENOWN_NETWORK_ID: ${PH_CONNECT_RENOWN_NETWORK_ID-eip155}
            PH_CONNECT_RENOWN_CHAIN_ID: ${PH_CONNECT_RENOWN_CHAIN_ID-1}
            PH_CONNECT_DISABLED_EDITORS: ${PH_CONNECT_DISABLED_EDITORS-}
            PH_CONNECT_SENTRY_DSN: ${PH_CONNECT_SENTRY_DSN-}
            PH_CONNECT_SENTRY_PROJECT: ${PH_CONNECT_SENTRY_PROJECT-}
            PH_CONNECT_SENTRY_ENV: ${PH_CONNECT_SENTRY_ENV-develop}
            PH_CONNECT_SENTRY_TRACING_ENABLED: ${PH_CONNECT_SENTRY_TRACING_ENABLED-false}
        ports:
            - ${CONNECT_PORT}:3000
